### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by Luke1505** [Luke1505/cccbridge#1]
- [ ] get the Github actions Stuff working for automatic building ad Release Appending
- [ ] get it working that the changelog is beeing copied and the jar + the Changelog is Published on Curseforge and Modrinth
- [ ] Start with Codename = W.A.N.Z.E
